
--데이터 값이 바뀌면
UPDATE TEAMW SET MEM_NAME = '태형'
WHERE MEM_NAME LIKE '태영';
DROP TABLE TEAMW;

--우리반

CREATE TABLE TEAMZ(
    TEAM_ID VARCHAR2(20) PRIMARY KEY,
    TEAM_NAME VARCHAR2(20)    
);
CREATE TABLE TEAMW(
    MEM_ID VARCHAR2(20) PRIMARY KEY,
    TEAM_ID VARCHAR2(20),
    MEM_NAME VARCHAR2(20),
    MEM_AGE DECIMAL,
    ROLL VARCHAR2(20)
);

ALTER TABLE TEAMW ADD (ROLL VARCHAR2(20)) ;

ALTER TABLE TEAMW ADD CONSTRAINT TEAMW_fk_TEAM_ID
      FOREIGN KEY (TEAM_ID) REFERENCES TEAMZ(TEAM_ID);
      
INSERT INTO TEAMZ(TEAM_ID,TEAM_NAME) VALUES( 'A','저스티스');
INSERT INTO TEAMZ(TEAM_ID,TEAM_NAME) VALUES( 'H','엘카로');
INSERT INTO TEAMZ(TEAM_ID,TEAM_NAME) VALUES( 'C','가오갤');
INSERT INTO TEAMZ(TEAM_ID,TEAM_NAME) VALUES( 'S','어벤저스');

INSERT INTO TEAMW VALUES ('01','A','형준','34');
INSERT INTO TEAMW VALUES ('02','A','세인','35');
INSERT INTO TEAMW VALUES ('03','A','희태','21');
INSERT INTO TEAMW VALUES ('04','A','상훈','29');
INSERT INTO TEAMW VALUES ('05','A','태형','25');
INSERT INTO TEAMW VALUES ('06','H','혜리','26');
INSERT INTO TEAMW VALUES ('07','H','지은','26');
INSERT INTO TEAMW VALUES ('08','H','준','27');
INSERT INTO TEAMW VALUES ('09','H','재경','30');
INSERT INTO TEAMW VALUES ('10','H','단아','26');
INSERT INTO TEAMW VALUES ('11','C','최정훈','32');
INSERT INTO TEAMW VALUES ('12','C','윤호','31');
INSERT INTO TEAMW VALUES ('13','C','가은','29');
INSERT INTO TEAMW VALUES ('14','C','정훈','23');
INSERT INTO TEAMW VALUES ('15','C','승태','30');
INSERT INTO TEAMW VALUES ('16','S','승호','27');
INSERT INTO TEAMW VALUES ('17','S','소진','26');
INSERT INTO TEAMW VALUES ('18','S','이슬','29');
INSERT INTO TEAMW VALUES ('19','S','진태','26');
INSERT INTO TEAMW VALUES ('20','S','누리','30');

--COUNT() 팀원수
SELECT
    COUNT(*) 팀원수
FROM
    TEAMW W
    JOIN TEAMZ Z
    ON W.TEAM_ID LIKE Z.TEAM_ID
GROUP BY Z.TEAM_ID
;



--SUM 나이합
SELECT
      (
    SELECT A.TEAM_NAME
    FROM TEAMZ A
    WHERE A.TEAM_ID LIKE Z.TEAM_ID
    ) 팀명,
    SUM(W.MEM_AGE) 나이합
FROM TEAMZ Z
    JOIN TEAMW W
    ON Z.TEAM_ID LIKE W.TEAM_ID
GROUP BY Z.TEAM_ID
;



--MAX 나이 최대치
SELECT
     Z.TEAM_ID 팀명,
    MAX(W.MEM_AGE) 나이최대치
FROM TEAMZ Z
    JOIN TEAMW W
    ON Z.TEAM_ID LIKE W.TEAM_ID
GROUP BY Z.TEAM_ID
;



SELECT
     Z.TEAM_ID 팀명,
    MIN(W.MEM_AGE) 나이최소치
FROM TEAMZ Z
    JOIN TEAMW W
    ON Z.TEAM_ID LIKE W.TEAM_ID
GROUP BY Z.TEAM_ID
;



SELECT
     Z.TEAM_ID 팀명,
    AVG(W.MEM_AGE) 나이평균
FROM TEAMZ Z
    JOIN TEAMW W
    ON Z.TEAM_ID LIKE W.TEAM_ID
GROUP BY Z.TEAM_ID
;


--롤 : 팀장, 회원담당, 아이템담당,게시판담당,관리자담당
--ALT 테이블 AND 칼럼



SELECT
    (SELECT A.TEAM_NAME
    FROM TEAMZ A
    WHERE A.TEAM_ID LIKE W.TEAM_ID) 팀명,
    COUNT(*) 팀원수,
    SUM(W.MEM_AGE) 나이합,
    AVG(W.MEM_AGE) 나이평균,
    MAX(W.MEM_AGE) 최대나이,
    MIN(W.MEM_AGE) 최소나이
FROM TEAMW W
GROUP BY W.TEAM_ID
ORDER BY W.TEAM_ID
;


--HAVING 사용
--평균 28이상
SELECT
    (SELECT A.TEAM_NAME
    FROM TEAMZ A
    WHERE A.TEAM_ID LIKE W.TEAM_ID) 팀명,
    COUNT(*) 팀원수,
    SUM(W.MEM_AGE) 나이합,
    AVG(W.MEM_AGE) 나이평균,
    MAX(W.MEM_AGE) 최대나이,
    MIN(W.MEM_AGE) 최소나이,
    팀장
FROM TEAMW W
GROUP BY W.TEAM_ID
HAVING AVG(W.MEM_AGE) >= 28
ORDER BY W.TEAM_ID
;


SELECT
    Z.TEAM_ID 팀ID,
    Z.TEAM_NAME 팀명,
    W.MEM_ID ID,
    W.MEM_NAME 이름,
    W.MEM_AGE 나이,
    W.ROLL 역할
FROM TEAW W
JOIN TEAMZ Z
ON W.TEAM_ID LIKE Z.TEME_ID
;

UPDATE TEAMW SET ROLL = 
CASE 
WHEN MEM_ID LIKE '01' THEN '팀장'
WHEN MEM_ID LIKE '06' THEN '팀장'
WHEN MEM_ID LIKE '11' THEN '팀장'
WHEN MEM_ID LIKE '16' THEN '팀장'
ELSE '팀원'
END
WHERE ROLL IS NULL;

SELECT * FROM TEAMW;








